name: Feature request
description: Suggest an idea to improve SwiftRest
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing an idea. Please describe the use case first.
  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What problem are you trying to solve?
      placeholder: As a developer, I want...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your preferred API/behavior.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other options did you evaluate?
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, examples, references
